spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5442/docker
    username: docker
    password: docker
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  # Replace by 'prod, faker' to add the faker context and have sample data loaded in production
  #liquibase:
  #  contexts: prod
  liquibase:
    change-log: classpath:config/liquibase/master.xml



server:
  port: 8080


application:
  serverURL: http://localhost:8080
  adminPassword: adminPassword
  adminEmail: adminEmail@adminEmail.com
  adminPrivateKey: adminPrivateKey
  adminPublicKey: adminPublicKey
  superAdminPrivateKey: superAdminPrivateKey
  superAdminPublicKey: superAdminPublicKey
  ImageServerPrivateKey: ImageServerPrivateKey
  ImageServerPublicKey: ImageServerPublicKey
  rabbitMQPrivateKey: rabbitMQPrivateKey
  rabbitMQPublicKey: rabbitMQPublicKey
  softwareSources: softwareSources/
  useHTTPInternally: true

  cytomine:
    defaultLanguage: ENGLISH
    imageServerURL: [http://imageServerURL/]
    messageBrokerServerURL: messageBrokerServerURL

    software:
      path:
        softwareImages: softwareImages/

  notification:
    email: email@email.com
    password: password
    smtpHost: host
    smtpPort: 1